# This is an example of the DAITSS configuration file restricted to
# the data necessary to run the describe service.
#
# You must set up your web server to set the environment variable
# DAITSS_CONFIG to point to a configuration file along these lines,
# though typically it will have sections for many services in addition
# to this one.
#
# Please don't use tabs in this file.

defaults:

# We normally name sections after the virtual hostname used by an
# applcation (this is so one physical host can run multiple services
# of the same kind).  An application's configuration code typically
# checks the VIRTUAL_HOSTNAME environment variable to determine the
# appropriate section to load.  Typically VIRTUAL_HOSTNAME is set in
# the same place that the DAITTS_CONFIG environment is set.

describe.example.org:
    log_syslog_facility:         LOG_LOCAL0
    log_filename:                describe.log
    max_pdf_bitstreams:          1000
    max_upload_file_size:        100MB    
    jvm_options: 
      - -Dhttp.proxyHost=localhost
      - -Dhttp.proxyPort=3128

# describe:log_syslog_facility
# -------------------------------
# If set, direct log information to this syslog facility (see
# /etc/syslog.conf). If neither log_filename nor log_syslog_facility
# are set, log to STDERR.
#
# describe:log_filename
# -------------------------------
# If set, direct log information to this file. If neither log_filename
# nor log_syslog_facility are set, log to STDERR.
##
# describe:max_pdf_bitstreams (optional)
# --------------------------
# Sets the maximum number of bitstreams per file describe will attempt to parse
##
# describe:max_upload_file_size (optional)
# --------------------------
# display the max file size for file upload.